/**
 * Beat Navigator QA Test Suite
 *
 * Tests the beat navigator dialog and floating button functionality:
 * - Floating button visibility on MEDIA/TEXT tabs
 * - Dialog opens with grid of beats (number, thumbnail, text)
 * - Clicking a beat scrolls to the correct position
 *
 * Usage:
 *   1. Start the app: yarn start
 *   2. Run: npx tsx test/manual_no_api_beat_navigator_qa.ts
 *
 * Environment variables:
 *   CDP_URL  - CDP endpoint (default: http://localhost:9222/)
 *   APP_URL  - App URL fragment to match (default: localhost:5175)
 */

import playwright, { type Browser, type BrowserContext, type Page, type ConsoleMessage } from "playwright";

// =====================================================================
// Config & Constants
// =====================================================================

const CONFIG = {
  CDP_RETRY_DELAY_MS: 1000,
  CDP_MAX_ATTEMPTS: 30,
  ACTION_DELAY_MS: 500,
  NAVIGATION_DELAY_MS: 1000,
  EDITOR_LOAD_DELAY_MS: 1500,
  EDITOR_SETTLE_DELAY_MS: 1500,
  PROJECT_CREATE_DELAY_MS: 3000,
  IMAGE_GENERATION_TIMEOUT_MS: 60000,
  DIALOG_CLOSE_DELAY_MS: 500,
} as const;

const BEAT_COUNT = 30;

const timestamp = new Date().toISOString().replace(/T/, " ").replace(/\..+/, "");
const runId = Date.now();
const TEST_PROJECT_TITLE = `[QA] BeatNavigator ${timestamp}`;
const TEST_PROJECT_DESCRIPTION = `Auto-generated by manual_no_api_beat_navigator_qa.ts (run ${runId}) – safe to delete`;

// =====================================================================
// Test MulmoScript with markdown beats
// =====================================================================

function createTestScript(): Record<string, unknown> {
  const beats = [];
  for (let i = 1; i <= BEAT_COUNT; i++) {
    beats.push({
      id: `${runId}-beat-${i}`,
      speaker: "Presenter",
      text: `Beat ${i} test text for navigator run ${runId}`,
      image: {
        type: "markdown",
        markdown: [
          `<div style='display:flex;flex-direction:column;justify-content:center;align-items:center;height:100vh;text-align:center;background:linear-gradient(135deg,hsl(${i * 60},70%,80%),hsl(${i * 60 + 30},70%,60%))'>`,
          "",
          `# Beat ${i}`,
          `## Navigator Test`,
          `Run: ${runId}`,
          "",
          "</div>",
        ],
      },
    });
  }

  return {
    $mulmocast: { version: "1.1" },
    title: TEST_PROJECT_TITLE,
    description: TEST_PROJECT_DESCRIPTION,
    lang: "en",
    speechParams: {
      speakers: {
        Presenter: {
          provider: "openai",
          voiceId: "alloy",
        },
      },
    },
    imageParams: {
      provider: "openai",
      images: {},
    },
    movieParams: {
      provider: "mock",
      model: "",
    },
    beats,
  };
}

// =====================================================================
// Results
// =====================================================================

interface TestResult {
  name: string;
  status: "PASS" | "FAIL" | "WARN";
  detail: string;
}
const results: TestResult[] = [];

function record(name: string, status: "PASS" | "FAIL" | "WARN", detail: string) {
  results.push({ name, status, detail });
  const icon = status === "PASS" ? "✓" : status === "FAIL" ? "✗" : "⚠";
  console.log(`  ${icon} [${status}] ${name}: ${detail}`);
}

// =====================================================================
// Infrastructure
// =====================================================================

async function connectCDP(): Promise<Browser> {
  const cdpUrl = process.env.CDP_URL || "http://localhost:9222/";
  let attempts = 0;
  while (attempts < CONFIG.CDP_MAX_ATTEMPTS) {
    try {
      const browser = await playwright.chromium.connectOverCDP(cdpUrl);
      console.log("✓ Connected to CDP");
      return browser;
    } catch (error: unknown) {
      attempts++;
      if (attempts === CONFIG.CDP_MAX_ATTEMPTS)
        throw new Error(
          `Failed after ${CONFIG.CDP_MAX_ATTEMPTS} attempts: ${error instanceof Error ? error.message : String(error)}`,
          { cause: error },
        );
      if (attempts === 1) console.log(`Connecting to ${cdpUrl}...`);
      await new Promise((r) => setTimeout(r, CONFIG.CDP_RETRY_DELAY_MS));
    }
  }
  throw new Error("Unreachable");
}

function findAppPage(contexts: BrowserContext[]): Page {
  const appUrl = process.env.APP_URL || "localhost:5175";
  for (const ctx of contexts) {
    const p = ctx.pages().find((pg) => pg.url().includes(appUrl));
    if (p) return p;
  }
  for (const ctx of contexts) {
    const p = ctx.pages().find((pg) => pg.url().includes("localhost:5173"));
    if (p) return p;
  }
  throw new Error("Could not find application page");
}

// =====================================================================
// Console Monitor
// =====================================================================

interface ConsoleMonitor {
  errors: string[];
  warnings: string[];
  start: () => void;
  stop: () => void;
}

function createConsoleMonitor(page: Page): ConsoleMonitor {
  const monitor: ConsoleMonitor = {
    errors: [],
    warnings: [],
    start: () => page.on("console", handler),
    stop: () => page.off("console", handler),
  };
  const handler = (msg: ConsoleMessage) => {
    if (msg.type() === "error") monitor.errors.push(msg.text());
    if (msg.type() === "warning") monitor.warnings.push(msg.text());
  };
  return monitor;
}

// =====================================================================
// Generic Helpers
// =====================================================================

const selectAllKey = process.platform === "darwin" ? "Meta+a" : "Control+a";
const pasteKey = process.platform === "darwin" ? "Meta+v" : "Control+v";
const copyKey = process.platform === "darwin" ? "Meta+c" : "Control+c";

async function clickTabByText(page: Page, tabText: string): Promise<boolean> {
  const tabs = await page.locator('[role="tab"]').all();
  for (const tab of tabs) {
    const text = (await tab.textContent())?.trim() || "";
    if (text === tabText || text.startsWith(tabText)) {
      await tab.click();
      await page.waitForTimeout(CONFIG.NAVIGATION_DELAY_MS);
      return true;
    }
  }
  return false;
}

async function navigateToBeatTab(page: Page): Promise<boolean> {
  const tabs = await page.locator('[role="tab"]').all();
  for (const tab of tabs) {
    const text = (await tab.textContent())?.trim() || "";
    if (text.startsWith("BEAT")) {
      await tab.click();
      await page.waitForTimeout(CONFIG.NAVIGATION_DELAY_MS);
      return true;
    }
  }
  return false;
}

async function navigateToTextTab(page: Page): Promise<boolean> {
  return (await clickTabByText(page, "Text")) || (await clickTabByText(page, "翻訳"));
}

// =====================================================================
// Monaco Helpers
// =====================================================================

async function readEditorJson(page: Page): Promise<Record<string, unknown> | null> {
  const viewLines = await page.$(".monaco-editor .view-lines");
  if (!viewLines) return null;
  await viewLines.click();
  await page.waitForTimeout(300);
  await page.keyboard.press(selectAllKey);
  await page.waitForTimeout(200);
  await page.keyboard.press(copyKey);
  await page.waitForTimeout(200);
  const text = await page.evaluate(() => window.electronAPI.readClipboardText());
  try {
    return JSON.parse(text);
  } catch {
    return null;
  }
}

async function writeEditorJson(page: Page, json: Record<string, unknown>): Promise<boolean> {
  const viewLines = await page.$(".monaco-editor .view-lines");
  if (!viewLines) return false;
  await viewLines.click();
  await page.waitForTimeout(300);
  await page.keyboard.press(selectAllKey);
  await page.waitForTimeout(200);
  await page.evaluate((t) => window.electronAPI.writeClipboardText(t), JSON.stringify(json, null, 2));
  await page.waitForTimeout(200);
  await page.keyboard.press(pasteKey);
  await page.waitForTimeout(2000);
  return true;
}

// =====================================================================
// Phase 1: Setup
// =====================================================================

async function phaseSetup(page: Page): Promise<boolean> {
  console.log("\n--- Phase 1: Setup ---");

  // Navigate to dashboard
  await page.goto(page.url().split("#")[0] + "#/");
  await page.waitForTimeout(CONFIG.NAVIGATION_DELAY_MS);

  // Close any overlay
  const overlay = await page.$('[data-state="open"][aria-hidden="true"]');
  if (overlay) {
    await page.keyboard.press("Escape");
    await page.waitForTimeout(CONFIG.ACTION_DELAY_MS);
  }

  // Create project
  const newBtn = await page.$('[data-testid="create-new-button"]');
  if (!newBtn) {
    record("Create project", "FAIL", "Create button not found");
    return false;
  }
  await newBtn.click();
  await page.waitForTimeout(CONFIG.PROJECT_CREATE_DELAY_MS);
  const created = page.url().includes("#/project/");
  record("Create project", created ? "PASS" : "FAIL", `URL: ${page.url()}`);
  if (!created) return false;

  // Write test script via JSON tab
  await clickTabByText(page, "JSON");
  await page.waitForTimeout(CONFIG.EDITOR_LOAD_DELAY_MS);

  const testScript = createTestScript();
  const written = await writeEditorJson(page, testScript);
  record("Write test script", written ? "PASS" : "FAIL", `${BEAT_COUNT} markdown beats`);
  if (!written) return false;

  // Verify beats were written
  const json = await readEditorJson(page);
  const beatCount = (json?.beats as unknown[])?.length ?? 0;
  record("Verify beats", beatCount === BEAT_COUNT ? "PASS" : "FAIL", `Expected ${BEAT_COUNT}, got ${beatCount}`);

  // Switch to BEAT tab and generate images via PDF Handout
  await page.waitForTimeout(CONFIG.EDITOR_SETTLE_DELAY_MS);
  await navigateToBeatTab(page);

  // Enable PDF Handout checkbox
  const pdfCheckbox = await page.evaluate(() => {
    const checkboxes = document.querySelectorAll('[role="checkbox"]');
    for (const cb of checkboxes) {
      const label = cb.parentElement?.textContent?.trim() || "";
      if (label.includes("PDF") && label.includes("Handout")) {
        if (cb.getAttribute("data-state") !== "checked") {
          (cb as HTMLElement).click();
        }
        return true;
      }
    }
    return false;
  });

  // Disable Movie first, then Podcast (order matters - Podcast is disabled while Movie is checked)
  await page.evaluate(() => {
    const checkboxes = document.querySelectorAll('[role="checkbox"]');
    for (const cb of checkboxes) {
      const label = cb.parentElement?.textContent?.trim() || "";
      if (label.includes("Movie") && cb.getAttribute("data-state") === "checked") {
        (cb as HTMLElement).click();
        break;
      }
    }
  });
  await page.waitForTimeout(CONFIG.ACTION_DELAY_MS);
  await page.evaluate(() => {
    const checkboxes = document.querySelectorAll('[role="checkbox"]');
    for (const cb of checkboxes) {
      const label = cb.parentElement?.textContent?.trim() || "";
      if (label.includes("Podcast") && cb.getAttribute("data-state") === "checked") {
        (cb as HTMLElement).click();
        break;
      }
    }
  });
  await page.waitForTimeout(CONFIG.ACTION_DELAY_MS);

  if (!pdfCheckbox) {
    record("Enable PDF Handout", "WARN", "PDF Handout checkbox not found, skipping image generation");
  } else {
    record("Enable PDF Handout", "PASS", "Enabled");

    // Click Generate Contents
    const generateBtn = await page.$('[data-testid="generate-contents-button"]');
    if (generateBtn) {
      await generateBtn.click();
      console.log("  ⏳ Generating images via PDF Handout...");

      // Wait for generation to complete (check for progress indicator disappearing)
      try {
        await page.waitForFunction(
          () => {
            const btn = document.querySelector('[data-testid="generate-contents-button"]');
            return btn && !btn.hasAttribute("disabled");
          },
          { timeout: CONFIG.IMAGE_GENERATION_TIMEOUT_MS },
        );
        record("Generate images", "PASS", "PDF Handout generation complete");
      } catch {
        record("Generate images", "WARN", "Generation may still be in progress or timed out");
      }
    } else {
      record("Generate images", "WARN", "Generate button not found");
    }
  }

  // Restore defaults: disable PDF Handout, re-enable Movie (which auto-enables Podcast)
  await page.evaluate(() => {
    const checkboxes = document.querySelectorAll('[role="checkbox"]');
    for (const cb of checkboxes) {
      const label = cb.parentElement?.textContent?.trim() || "";
      if (label.includes("PDF") && label.includes("Handout") && cb.getAttribute("data-state") === "checked") {
        (cb as HTMLElement).click();
      }
    }
  });
  await page.waitForTimeout(CONFIG.ACTION_DELAY_MS);
  await page.evaluate(() => {
    const checkboxes = document.querySelectorAll('[role="checkbox"]');
    for (const cb of checkboxes) {
      const label = cb.parentElement?.textContent?.trim() || "";
      if (label.includes("Movie") && cb.getAttribute("data-state") !== "checked") {
        (cb as HTMLElement).click();
      }
    }
  });

  return true;
}

// =====================================================================
// Phase 2: Beat Navigator on MEDIA tab
// =====================================================================

async function phaseMediaTab(page: Page): Promise<void> {
  console.log("\n--- Phase 2: Beat Navigator - MEDIA tab ---");

  await navigateToBeatTab(page);
  await page.waitForTimeout(CONFIG.ACTION_DELAY_MS);

  // Test: Floating button exists
  const mediaBtn = await page.$('[data-testid="beat-navigator-button-media"]');
  record("Floating button (MEDIA)", mediaBtn ? "PASS" : "FAIL", mediaBtn ? "Found" : "Not found");
  if (!mediaBtn) return;

  // Test: Open dialog
  await mediaBtn.click();
  await page.waitForTimeout(CONFIG.ACTION_DELAY_MS);

  const dialog = await page.$('[role="dialog"]');
  record("Dialog opens", dialog ? "PASS" : "FAIL", dialog ? "Dialog visible" : "Dialog not found");
  if (!dialog) return;

  // Test: Correct number of beats in dialog
  const dialogButtons = await dialog.$$("button:not([class*='Close'])");
  // Filter out the Close button - count only beat buttons
  const beatButtons = [];
  for (const btn of dialogButtons) {
    const text = (await btn.textContent()) || "";
    if (text.includes("Beat")) {
      beatButtons.push(btn);
    }
  }
  record(
    "Dialog beat count",
    beatButtons.length === BEAT_COUNT ? "PASS" : "FAIL",
    `Expected ${BEAT_COUNT}, got ${beatButtons.length}`,
  );

  // Prepare dialog scroll viewport for wheel tests
  const mediaViewportReady = await dialog.evaluate((el) => {
    const candidates = Array.from(el.querySelectorAll<HTMLElement>("*")).filter(
      (node) => node.scrollHeight - node.clientHeight > 10,
    );
    if (candidates.length === 0) return false;
    const viewport = candidates.sort((a, b) => b.scrollHeight - b.clientHeight - (a.scrollHeight - a.clientHeight))[0];
    viewport.setAttribute("data-qa-dialog-scroll", "media");
    viewport.scrollTop = 0;
    return true;
  });

  // Test: Scroll inside dialog (down/up)
  const mediaDialogScroll = await dialog.evaluate((el) => {
    const candidates = Array.from(el.querySelectorAll<HTMLElement>("*")).filter(
      (node) => node.scrollHeight - node.clientHeight > 10,
    );
    if (candidates.length === 0) return null;

    const viewport = candidates.sort((a, b) => b.scrollHeight - b.clientHeight - (a.scrollHeight - a.clientHeight))[0];
    const before = viewport.scrollTop;
    const maxTop = Math.max(0, viewport.scrollHeight - viewport.clientHeight);
    viewport.scrollTop = Math.min(maxTop, before + Math.max(120, Math.floor(viewport.clientHeight * 0.8)));
    const afterDown = viewport.scrollTop;
    viewport.scrollTop = 0;
    const afterUp = viewport.scrollTop;
    return { before, afterDown, afterUp, maxTop };
  });

  record(
    "Dialog scroll down (MEDIA)",
    !!mediaDialogScroll && mediaDialogScroll.afterDown > mediaDialogScroll.before ? "PASS" : "FAIL",
    mediaDialogScroll
      ? `scrollTop: ${mediaDialogScroll.before} → ${mediaDialogScroll.afterDown}`
      : "No scrollable viewport found",
  );
  record(
    "Dialog scroll up (MEDIA)",
    !!mediaDialogScroll && mediaDialogScroll.afterUp === 0 ? "PASS" : "FAIL",
    mediaDialogScroll ? `scrollTop after up: ${mediaDialogScroll.afterUp}` : "No scrollable viewport found",
  );

  // Test: Mouse wheel scroll inside dialog (down/up)
  if (mediaViewportReady) {
    const viewport = page.locator('[data-qa-dialog-scroll="media"]').first();
    const box = await viewport.boundingBox();
    if (box) {
      await page.mouse.move(box.x + box.width / 2, box.y + Math.min(40, box.height / 2));
      const wheelBefore = await page.evaluate(() => {
        const el = document.querySelector('[data-qa-dialog-scroll="media"]') as HTMLElement | null;
        return el?.scrollTop ?? -1;
      });
      await page.mouse.wheel(0, 700);
      await page.waitForTimeout(200);
      const wheelAfterDown = await page.evaluate(() => {
        const el = document.querySelector('[data-qa-dialog-scroll="media"]') as HTMLElement | null;
        return el?.scrollTop ?? -1;
      });
      await page.mouse.wheel(0, -700);
      await page.waitForTimeout(200);
      const wheelAfterUp = await page.evaluate(() => {
        const el = document.querySelector('[data-qa-dialog-scroll="media"]') as HTMLElement | null;
        return el?.scrollTop ?? -1;
      });
      record(
        "Dialog wheel scroll down (MEDIA)",
        wheelAfterDown > wheelBefore ? "PASS" : "FAIL",
        `scrollTop: ${wheelBefore} → ${wheelAfterDown}`,
      );
      record(
        "Dialog wheel scroll up (MEDIA)",
        wheelAfterUp < wheelAfterDown ? "PASS" : "FAIL",
        `scrollTop: ${wheelAfterDown} → ${wheelAfterUp}`,
      );
    } else {
      record("Dialog wheel scroll down (MEDIA)", "FAIL", "Scrollable viewport not interactable");
      record("Dialog wheel scroll up (MEDIA)", "FAIL", "Scrollable viewport not interactable");
    }
  } else {
    record("Dialog wheel scroll down (MEDIA)", "FAIL", "No scrollable viewport found");
    record("Dialog wheel scroll up (MEDIA)", "FAIL", "No scrollable viewport found");
  }

  // Test: Each beat has thumbnail (image or placeholder)
  const thumbnailCount = await dialog.evaluate((el) => {
    return el.querySelectorAll("img, svg").length;
  });
  record("Thumbnails present", thumbnailCount >= BEAT_COUNT ? "PASS" : "WARN", `Found ${thumbnailCount} images/icons`);

  // Test: Beat text is displayed
  const hasText = await dialog.evaluate((el, rid) => {
    const paragraphs = el.querySelectorAll("p");
    for (const p of paragraphs) {
      if (p.textContent?.includes(`run ${rid}`)) return true;
    }
    return false;
  }, runId.toString());
  record(
    "Beat text displayed",
    hasText ? "PASS" : "FAIL",
    hasText ? "Test text found in dialog" : "Test text not found",
  );

  // Test: Last beat card is clickable when dialog is scrolled to bottom
  await page.evaluate(() => {
    const el = document.querySelector('[data-qa-dialog-scroll="media"]') as HTMLElement | null;
    if (!el) return;
    el.scrollTop = el.scrollHeight - el.clientHeight;
  });
  await page.waitForTimeout(200);

  // First, record initial editor scroll position
  const scrollBefore = await page.evaluate(() => {
    const container = document
      .querySelector('[data-testid="beat-navigator-button-media"]')
      ?.closest(".overflow-y-auto");
    return container?.scrollTop ?? -1;
  });

  // Click last beat button from bottom of dialog
  if (beatButtons.length > 0) {
    const lastBeatBtn = beatButtons[beatButtons.length - 1];
    await lastBeatBtn.click();

    // Wait for dialog close + scroll
    await page.waitForTimeout(CONFIG.DIALOG_CLOSE_DELAY_MS + 500);

    const scrollAfter = await page.evaluate(() => {
      const container = document
        .querySelector('[data-testid="beat-navigator-button-media"]')
        ?.closest(".overflow-y-auto");
      return container?.scrollTop ?? -1;
    });

    const lastBeatId = `${runId}-beat-${BEAT_COUNT}`;
    const lastBeatVisible = await page.evaluate((beatId) => {
      const el = document.querySelector(`[data-beat-id="${beatId}"]`);
      const container = el?.closest(".overflow-y-auto");
      if (!el || !container) return false;
      const cRect = container.getBoundingClientRect();
      const eRect = el.getBoundingClientRect();
      return eRect.top >= cRect.top - 50 && eRect.top <= cRect.bottom + 50;
    }, lastBeatId);

    record(
      "Last beat clickable at dialog bottom (MEDIA)",
      lastBeatVisible ? "PASS" : scrollAfter !== scrollBefore ? "WARN" : "FAIL",
      `scrollTop: ${scrollBefore} → ${scrollAfter}, beat visible: ${lastBeatVisible}`,
    );
  }

  // Test: Navigate to beat 5
  const navBtn2 = await page.$('[data-testid="beat-navigator-button-media"]');
  if (navBtn2) {
    await navBtn2.click();
    await page.waitForTimeout(CONFIG.ACTION_DELAY_MS);

    const dialog2 = await page.$('[role="dialog"]');
    if (dialog2) {
      const beat5Btns = [];
      const allBtns = await dialog2.$$("button");
      for (const btn of allBtns) {
        const text = (await btn.textContent()) || "";
        if (text.includes("Beat 5")) {
          beat5Btns.push(btn);
          break;
        }
      }

      if (beat5Btns.length > 0) {
        const scrollBeforeBeat5 = await page.evaluate(() => {
          const container = document
            .querySelector('[data-testid="beat-navigator-button-media"]')
            ?.closest(".overflow-y-auto");
          return container?.scrollTop ?? -1;
        });

        await beat5Btns[0].click();
        await page.waitForTimeout(CONFIG.DIALOG_CLOSE_DELAY_MS + 500);

        const scrollAfterBeat5 = await page.evaluate(() => {
          const container = document
            .querySelector('[data-testid="beat-navigator-button-media"]')
            ?.closest(".overflow-y-auto");
          return container?.scrollTop ?? -1;
        });

        const beat5Id = `${runId}-beat-5`;
        const beat5Visible = await page.evaluate((beatId) => {
          const el = document.querySelector(`[data-beat-id="${beatId}"]`);
          const container = el?.closest(".overflow-y-auto");
          if (!el || !container) return false;
          const cRect = container.getBoundingClientRect();
          const eRect = el.getBoundingClientRect();
          return eRect.top >= cRect.top - 50 && eRect.top <= cRect.bottom + 50;
        }, beat5Id);

        record(
          "Scroll to beat 5 (MEDIA)",
          beat5Visible ? "PASS" : scrollAfterBeat5 !== scrollBeforeBeat5 ? "WARN" : "FAIL",
          `scrollTop: ${scrollBeforeBeat5} → ${scrollAfterBeat5}, beat visible: ${beat5Visible}`,
        );
      }
    }
  }

  // Test: Navigate to first beat (after beat 5)
  const navBtn3 = await page.$('[data-testid="beat-navigator-button-media"]');
  if (navBtn3) {
    await navBtn3.click();
    await page.waitForTimeout(CONFIG.ACTION_DELAY_MS);

    const dialog3 = await page.$('[role="dialog"]');
    if (dialog3) {
      const firstBeatBtns = [];
      const allBtns3 = await dialog3.$$("button");
      for (const btn of allBtns3) {
        const text = (await btn.textContent()) || "";
        if (text.includes("Beat 1")) {
          firstBeatBtns.push(btn);
          break;
        }
      }

      if (firstBeatBtns.length > 0) {
        await firstBeatBtns[0].click();
        await page.waitForTimeout(CONFIG.DIALOG_CLOSE_DELAY_MS + 500);

        const firstBeatId = `${runId}-beat-1`;
        const firstBeatVisible = await page.evaluate((beatId) => {
          const el = document.querySelector(`[data-beat-id="${beatId}"]`);
          const container = el?.closest(".overflow-y-auto");
          if (!el || !container) return false;
          const cRect = container.getBoundingClientRect();
          const eRect = el.getBoundingClientRect();
          return eRect.top >= cRect.top - 50 && eRect.top <= cRect.bottom + 50;
        }, firstBeatId);

        record(
          "Scroll to first beat (MEDIA)",
          firstBeatVisible ? "PASS" : "FAIL",
          `Beat 1 visible: ${firstBeatVisible}`,
        );
      }
    }
  }
}

// =====================================================================
// Phase 3: Beat Navigator on TEXT tab
// =====================================================================

async function phaseTextTab(page: Page): Promise<void> {
  console.log("\n--- Phase 3: Beat Navigator - TEXT tab ---");

  await navigateToTextTab(page);
  await page.waitForTimeout(CONFIG.ACTION_DELAY_MS);

  // Test: Floating button exists
  const textBtn = await page.$('[data-testid="beat-navigator-button-text"]');
  record("Floating button (TEXT)", textBtn ? "PASS" : "FAIL", textBtn ? "Found" : "Not found");
  if (!textBtn) return;

  // Test: Open dialog and navigate
  await textBtn.click();
  await page.waitForTimeout(CONFIG.ACTION_DELAY_MS);

  const dialog = await page.$('[role="dialog"]');
  record("Dialog opens (TEXT)", dialog ? "PASS" : "FAIL", dialog ? "Dialog visible" : "Dialog not found");
  if (!dialog) return;

  // Collect beat buttons in dialog
  const beatButtons = [];
  const allBtns = await dialog.$$("button");
  for (const btn of allBtns) {
    const text = (await btn.textContent()) || "";
    if (text.includes("Beat")) {
      beatButtons.push(btn);
    }
  }

  // Prepare dialog scroll viewport for wheel tests
  const textViewportReady = await dialog.evaluate((el) => {
    const candidates = Array.from(el.querySelectorAll<HTMLElement>("*")).filter(
      (node) => node.scrollHeight - node.clientHeight > 10,
    );
    if (candidates.length === 0) return false;
    const viewport = candidates.sort((a, b) => b.scrollHeight - b.clientHeight - (a.scrollHeight - a.clientHeight))[0];
    viewport.setAttribute("data-qa-dialog-scroll", "text");
    viewport.scrollTop = 0;
    return true;
  });

  // Test: Scroll inside dialog (down/up)
  const textDialogScroll = await dialog.evaluate((el) => {
    const candidates = Array.from(el.querySelectorAll<HTMLElement>("*")).filter(
      (node) => node.scrollHeight - node.clientHeight > 10,
    );
    if (candidates.length === 0) return null;

    const viewport = candidates.sort((a, b) => b.scrollHeight - b.clientHeight - (a.scrollHeight - a.clientHeight))[0];
    const before = viewport.scrollTop;
    const maxTop = Math.max(0, viewport.scrollHeight - viewport.clientHeight);
    viewport.scrollTop = Math.min(maxTop, before + Math.max(120, Math.floor(viewport.clientHeight * 0.8)));
    const afterDown = viewport.scrollTop;
    viewport.scrollTop = 0;
    const afterUp = viewport.scrollTop;
    return { before, afterDown, afterUp, maxTop };
  });

  record(
    "Dialog scroll down (TEXT)",
    !!textDialogScroll && textDialogScroll.afterDown > textDialogScroll.before ? "PASS" : "FAIL",
    textDialogScroll
      ? `scrollTop: ${textDialogScroll.before} → ${textDialogScroll.afterDown}`
      : "No scrollable viewport found",
  );
  record(
    "Dialog scroll up (TEXT)",
    !!textDialogScroll && textDialogScroll.afterUp === 0 ? "PASS" : "FAIL",
    textDialogScroll ? `scrollTop after up: ${textDialogScroll.afterUp}` : "No scrollable viewport found",
  );

  // Test: Mouse wheel scroll inside dialog (down/up)
  if (textViewportReady) {
    const viewport = page.locator('[data-qa-dialog-scroll="text"]').first();
    const box = await viewport.boundingBox();
    if (box) {
      await page.mouse.move(box.x + box.width / 2, box.y + Math.min(40, box.height / 2));
      const wheelBefore = await page.evaluate(() => {
        const el = document.querySelector('[data-qa-dialog-scroll="text"]') as HTMLElement | null;
        return el?.scrollTop ?? -1;
      });
      await page.mouse.wheel(0, 700);
      await page.waitForTimeout(200);
      const wheelAfterDown = await page.evaluate(() => {
        const el = document.querySelector('[data-qa-dialog-scroll="text"]') as HTMLElement | null;
        return el?.scrollTop ?? -1;
      });
      await page.mouse.wheel(0, -700);
      await page.waitForTimeout(200);
      const wheelAfterUp = await page.evaluate(() => {
        const el = document.querySelector('[data-qa-dialog-scroll="text"]') as HTMLElement | null;
        return el?.scrollTop ?? -1;
      });
      record(
        "Dialog wheel scroll down (TEXT)",
        wheelAfterDown > wheelBefore ? "PASS" : "FAIL",
        `scrollTop: ${wheelBefore} → ${wheelAfterDown}`,
      );
      record(
        "Dialog wheel scroll up (TEXT)",
        wheelAfterUp < wheelAfterDown ? "PASS" : "FAIL",
        `scrollTop: ${wheelAfterDown} → ${wheelAfterUp}`,
      );
    } else {
      record("Dialog wheel scroll down (TEXT)", "FAIL", "Scrollable viewport not interactable");
      record("Dialog wheel scroll up (TEXT)", "FAIL", "Scrollable viewport not interactable");
    }
  } else {
    record("Dialog wheel scroll down (TEXT)", "FAIL", "No scrollable viewport found");
    record("Dialog wheel scroll up (TEXT)", "FAIL", "No scrollable viewport found");
  }

  // Test: Last beat card is clickable when dialog is scrolled to bottom
  await page.evaluate(() => {
    const el = document.querySelector('[data-qa-dialog-scroll="text"]') as HTMLElement | null;
    if (!el) return;
    el.scrollTop = el.scrollHeight - el.clientHeight;
  });
  await page.waitForTimeout(200);

  if (beatButtons.length > 0) {
    const scrollBeforeLast = await page.evaluate(() => {
      const container = document
        .querySelector('[data-testid="beat-navigator-button-text"]')
        ?.closest(".overflow-y-auto");
      return container?.scrollTop ?? -1;
    });

    const lastBeatBtn = beatButtons[beatButtons.length - 1];
    await lastBeatBtn.click();
    await page.waitForTimeout(CONFIG.DIALOG_CLOSE_DELAY_MS + 500);

    const scrollAfterLast = await page.evaluate(() => {
      const container = document
        .querySelector('[data-testid="beat-navigator-button-text"]')
        ?.closest(".overflow-y-auto");
      return container?.scrollTop ?? -1;
    });

    const lastBeatId = `${runId}-beat-${BEAT_COUNT}`;
    const lastBeatVisible = await page.evaluate((beatId) => {
      const el = document.querySelector(`[data-beat-id="${beatId}"]`);
      const container = el?.closest(".overflow-y-auto");
      if (!el || !container) return false;
      const cRect = container.getBoundingClientRect();
      const eRect = el.getBoundingClientRect();
      return eRect.top >= cRect.top - 50 && eRect.top <= cRect.bottom + 50;
    }, lastBeatId);

    record(
      "Last beat clickable at dialog bottom (TEXT)",
      lastBeatVisible ? "PASS" : scrollAfterLast !== scrollBeforeLast ? "WARN" : "FAIL",
      `scrollTop: ${scrollBeforeLast} → ${scrollAfterLast}, beat visible: ${lastBeatVisible}`,
    );
  }

  // Re-open dialog for explicit beat 5 navigation check
  const textBtn2 = await page.$('[data-testid="beat-navigator-button-text"]');
  if (!textBtn2) {
    record("Scroll to beat 5 (TEXT)", "FAIL", "Navigator button not found after bottom-click test");
    return;
  }
  await textBtn2.click();
  await page.waitForTimeout(CONFIG.ACTION_DELAY_MS);

  const dialogForBeat5 = await page.$('[role="dialog"]');
  if (!dialogForBeat5) {
    record("Scroll to beat 5 (TEXT)", "FAIL", "Dialog not found after re-open");
    return;
  }

  const beatButtonsForBeat5 = [];
  const allBtnsForBeat5 = await dialogForBeat5.$$("button");
  for (const btn of allBtnsForBeat5) {
    const text = (await btn.textContent()) || "";
    if (text.includes("Beat")) {
      beatButtonsForBeat5.push(btn);
    }
  }

  // Click beat 5 (second to last)
  const targetBeatIndex = 4; // 0-based

  if (beatButtonsForBeat5.length > targetBeatIndex) {
    const scrollBefore = await page.evaluate(() => {
      const container = document
        .querySelector('[data-testid="beat-navigator-button-text"]')
        ?.closest(".overflow-y-auto");
      return container?.scrollTop ?? -1;
    });

    await beatButtonsForBeat5[targetBeatIndex].click();
    await page.waitForTimeout(CONFIG.DIALOG_CLOSE_DELAY_MS + 500);

    const scrollAfter = await page.evaluate(() => {
      const container = document
        .querySelector('[data-testid="beat-navigator-button-text"]')
        ?.closest(".overflow-y-auto");
      return container?.scrollTop ?? -1;
    });

    const targetBeatId = `${runId}-beat-${targetBeatIndex + 1}`;
    const targetVisible = await page.evaluate((beatId) => {
      const el = document.querySelector(`[data-beat-id="${beatId}"]`);
      const container = el?.closest(".overflow-y-auto");
      if (!el || !container) return false;
      const cRect = container.getBoundingClientRect();
      const eRect = el.getBoundingClientRect();
      return eRect.top >= cRect.top - 50 && eRect.top <= cRect.bottom + 50;
    }, targetBeatId);

    record(
      "Scroll to beat 5 (TEXT)",
      targetVisible ? "PASS" : scrollAfter !== scrollBefore ? "WARN" : "FAIL",
      `scrollTop: ${scrollBefore} → ${scrollAfter}, beat visible: ${targetVisible}`,
    );

    // Test: Navigate back to first beat on TEXT tab
    const navBtn2 = await page.$('[data-testid="beat-navigator-button-text"]');
    if (navBtn2) {
      await navBtn2.click();
      await page.waitForTimeout(CONFIG.ACTION_DELAY_MS);

      const dialog2 = await page.$('[role="dialog"]');
      if (dialog2) {
        const firstBeatBtns = [];
        const allBtns2 = await dialog2.$$("button");
        for (const btn of allBtns2) {
          const text = (await btn.textContent()) || "";
          if (text.includes("Beat 1")) {
            firstBeatBtns.push(btn);
            break;
          }
        }

        if (firstBeatBtns.length > 0) {
          await firstBeatBtns[0].click();
          await page.waitForTimeout(CONFIG.DIALOG_CLOSE_DELAY_MS + 500);

          const firstBeatId = `${runId}-beat-1`;
          const firstBeatVisible = await page.evaluate((beatId) => {
            const el = document.querySelector(`[data-beat-id="${beatId}"]`);
            const container = el?.closest(".overflow-y-auto");
            if (!el || !container) return false;
            const cRect = container.getBoundingClientRect();
            const eRect = el.getBoundingClientRect();
            return eRect.top >= cRect.top - 50 && eRect.top <= cRect.bottom + 50;
          }, firstBeatId);

          record(
            "Scroll to first beat (TEXT)",
            firstBeatVisible ? "PASS" : "FAIL",
            `Beat 1 visible: ${firstBeatVisible}`,
          );
        }
      }
    }
  } else {
    record("Scroll to beat 5 (TEXT)", "FAIL", `Only ${beatButtons.length} beat buttons found`);
  }
}

// =====================================================================
// Phase 4: Health
// =====================================================================

async function phaseHealth(monitor: ConsoleMonitor): Promise<void> {
  console.log("\n--- Phase 4: Health ---");

  const filteredErrors = monitor.errors.filter(
    (e) => !e.includes("Electron Security Warning") && !e.includes("net::ERR_"),
  );

  record(
    "Console errors",
    filteredErrors.length === 0 ? "PASS" : "FAIL",
    filteredErrors.length === 0 ? "No errors" : `${filteredErrors.length} error(s)`,
  );
  filteredErrors.forEach((e) => console.log(`    ERROR: ${e.substring(0, 200)}`));
}

// =====================================================================
// Main
// =====================================================================

(async () => {
  console.log(`\nBeat Navigator QA Test Suite`);
  console.log(`Run ID: ${runId}`);
  console.log(`${"=".repeat(50)}`);

  let browser: Browser | undefined;
  let exitCode = 0;

  try {
    browser = await connectCDP();
    const page = findAppPage(browser.contexts());
    const monitor = createConsoleMonitor(page);
    monitor.start();

    const setupOk = await phaseSetup(page);
    if (setupOk) {
      await phaseMediaTab(page);
      await phaseTextTab(page);
    }

    monitor.stop();
    await phaseHealth(monitor);
  } catch (error: unknown) {
    console.error("\n✗ Fatal error:", error instanceof Error ? error.message : String(error));
    exitCode = 1;
  } finally {
    if (browser) await browser.close();
  }

  // Summary
  const passed = results.filter((r) => r.status === "PASS").length;
  const failed = results.filter((r) => r.status === "FAIL").length;
  const warned = results.filter((r) => r.status === "WARN").length;

  console.log(`\n${"=".repeat(50)}`);
  console.log(`  Results: ${passed} PASS / ${failed} FAIL / ${warned} WARN`);
  console.log(`${"=".repeat(50)}`);

  if (failed > 0) {
    console.log("\nFailed tests:");
    results
      .filter((r) => r.status === "FAIL")
      .forEach((r) => {
        console.log(`  ✗ ${r.name}: ${r.detail}`);
      });
    exitCode = 1;
  }

  process.exit(exitCode);
})();
