/**
 * Concurrency QA Test Suite (no API cost)
 *
 * Manual test script to verify the Concurrency feature added in
 * receptron/mulmocast-app#1618:
 *
 *   - Settings page: "Concurrency Defaults" card (image/movie + audio)
 *   - Project Style tab: "Concurrency" card (per-project override)
 *   - createProject: global defaults are injected once at creation time
 *     into script.imageParams / movieParams / audioParams .concurrency
 *   - Re-opening an existing project does NOT mutate it
 *
 *   Phase 1 – Settings
 *     1a. Section exists, fields are present, blank state
 *     1b. Set values, verify persistence (close & reopen modal)
 *
 *   Phase 2 – Inject on create (Settings set)
 *     2a. Create a new project with image/movie=A, audio=B → JSON has those
 *
 *   Phase 3 – Inject on create (Settings blank)
 *     3a. Clear Settings, create a new project → JSON has no concurrency fields
 *
 *   Phase 4 – Existing project untouched
 *     4a. Re-set Settings to non-blank, navigate away from the Phase 3 project
 *         and back → JSON still has no concurrency fields (no mutation on open)
 *
 *   Phase 5 – Style tab per-project edits
 *     5a. image/movie input writes the same value to imageParams + movieParams
 *     5b. audio input writes audioParams.concurrency
 *     5c. clearing inputs removes the concurrency fields from JSON
 *
 *   Phase 6 – JSON → UI round-trip
 *     6a. Editing JSON updates the Style tab inputs
 *
 *   Phase 7 – Console health
 *
 * Usage:
 *   1. Start the app: yarn start
 *   2. Run: npx tsx test/manual_no_api_concurrency_qa.ts
 *
 * Environment variables:
 *   CDP_URL  - CDP endpoint (default: http://localhost:9222/)
 *   APP_URL  - App URL fragment to match (default: localhost:5175)
 */
import playwright, { Browser, BrowserContext, ConsoleMessage, Page } from "playwright-core";

const CONFIG = {
  CDP_RETRY_DELAY_MS: 1000,
  CDP_MAX_ATTEMPTS: 30,
  ACTION_DELAY_MS: 500,
  NAVIGATION_DELAY_MS: 1000,
  EDITOR_LOAD_DELAY_MS: 1500,
  SETTINGS_SAVE_DELAY_MS: 2000,
  PROJECT_CREATE_DELAY_MS: 3000,
  /** Wait before leaving JSON tab so Monaco can finish async ops (diagnostics, validation) */
  EDITOR_SETTLE_DELAY_MS: 1500,
} as const;

const timestamp = new Date().toISOString().replace(/T/, " ").replace(/\..+/, "");
const runId = Date.now();

// Test values — change every run so leftover settings cannot mask a bug
const IMAGE_MOVIE_VALUES = [3, 5, 7, 11];
const AUDIO_VALUES = [2, 4, 6, 8];
const TEST_IMAGE_MOVIE = IMAGE_MOVIE_VALUES[runId % IMAGE_MOVIE_VALUES.length];
const TEST_AUDIO = AUDIO_VALUES[runId % AUDIO_VALUES.length];
const TEST_IMAGE_MOVIE_2 = IMAGE_MOVIE_VALUES[(runId + 1) % IMAGE_MOVIE_VALUES.length];
const TEST_AUDIO_2 = AUDIO_VALUES[(runId + 1) % AUDIO_VALUES.length];

// Override values for the Style-tab edits (must differ from the global)
const OVERRIDE_IMAGE_MOVIE = TEST_IMAGE_MOVIE === 9 ? 10 : 9;
const OVERRIDE_AUDIO = TEST_AUDIO === 5 ? 6 : 5;

const TITLE_INJECT = `[QA] Concurrency Inject ${timestamp}`;
const TITLE_BLANK = `[QA] Concurrency Blank ${timestamp}`;
const TEST_DESCRIPTION = `Auto-generated by manual_no_api_concurrency_qa.ts (run ${runId}) – safe to delete`;

interface TestResult {
  name: string;
  status: "PASS" | "FAIL" | "WARN";
  detail: string;
}

const results: TestResult[] = [];

function record(name: string, status: "PASS" | "FAIL" | "WARN", detail: string) {
  results.push({ name, status, detail });
  const icon = status === "PASS" ? "✓" : status === "FAIL" ? "✗" : "⚠";
  console.log(`  ${icon} [${status}] ${name}: ${detail}`);
}

// --- Infrastructure ---

async function connectCDP(): Promise<Browser> {
  const cdpUrl = process.env.CDP_URL || "http://localhost:9222/";
  let attempts = 0;

  while (attempts < CONFIG.CDP_MAX_ATTEMPTS) {
    try {
      const browser = await playwright.chromium.connectOverCDP(cdpUrl);
      console.log("✓ Connected to CDP");
      return browser;
    } catch (error: unknown) {
      attempts++;
      if (attempts === CONFIG.CDP_MAX_ATTEMPTS) {
        throw new Error(
          `Failed to connect after ${CONFIG.CDP_MAX_ATTEMPTS} attempts: ${error instanceof Error ? error.message : String(error)}`,
          { cause: error },
        );
      }
      if (attempts === 1) {
        console.log(`Connecting to ${cdpUrl}...`);
      }
      await new Promise((resolve) => setTimeout(resolve, CONFIG.CDP_RETRY_DELAY_MS));
    }
  }
  throw new Error("Unreachable");
}

function findAppPage(contexts: BrowserContext[]): Page {
  const appUrl = process.env.APP_URL || "localhost:5175";
  for (const context of contexts) {
    const page = context.pages().find((p) => p.url().includes(appUrl));
    if (page) return page;
  }
  // fallback: try 5173
  for (const context of contexts) {
    const page = context.pages().find((p) => p.url().includes("localhost:5173"));
    if (page) return page;
  }
  throw new Error("Could not find application page");
}

// --- Console Monitoring ---

interface ConsoleMonitor {
  errors: string[];
  warnings: string[];
  start: () => void;
  stop: () => void;
  reset: () => void;
}

function createConsoleMonitor(page: Page): ConsoleMonitor {
  const monitor: ConsoleMonitor = {
    errors: [],
    warnings: [],
    start: () => {
      page.on("console", handler);
    },
    stop: () => {
      page.off("console", handler);
    },
    reset: () => {
      monitor.errors = [];
      monitor.warnings = [];
    },
  };

  const handler = (msg: ConsoleMessage) => {
    const text = msg.text();
    const type = msg.type();
    if (type === "error") monitor.errors.push(text);
    if (type === "warning") monitor.warnings.push(text);
  };

  return monitor;
}

// --- Helpers ---

const selectAllKey = process.platform === "darwin" ? "Meta+a" : "Control+a";
const copyKey = process.platform === "darwin" ? "Meta+c" : "Control+c";
const pasteKey = process.platform === "darwin" ? "Meta+v" : "Control+v";

async function clickTabByText(page: Page, tabText: string): Promise<boolean> {
  const tabs = await page.locator('[role="tab"]').all();
  for (const tab of tabs) {
    const text = await tab.textContent();
    if (text?.trim() === tabText) {
      await tab.click();
      await page.waitForTimeout(CONFIG.NAVIGATION_DELAY_MS);
      return true;
    }
  }
  return false;
}

async function navigateToStyleTab(page: Page): Promise<boolean> {
  return (await clickTabByText(page, "スタイル")) || (await clickTabByText(page, "Style"));
}

async function navigateToJsonTab(page: Page): Promise<boolean> {
  // JSON is the same in both languages
  if (await clickTabByText(page, "JSON")) {
    await page.waitForTimeout(CONFIG.EDITOR_LOAD_DELAY_MS);
    return true;
  }
  return false;
}

async function scrollToH4(page: Page, heading: string): Promise<boolean> {
  return page.evaluate((h) => {
    const h4s = document.querySelectorAll("h4");
    for (const el of h4s) {
      if (el.textContent?.trim() === h) {
        el.scrollIntoView({ behavior: "instant", block: "start" });
        return true;
      }
    }
    return false;
  }, heading);
}

async function scrollToConcurrencySection(page: Page): Promise<boolean> {
  return (await scrollToH4(page, "並列実行設定")) || (await scrollToH4(page, "Concurrency"));
}

/**
 * Read the value of a number input whose <Label> matches the given text,
 * scoped to the Concurrency section (h4 = "並列実行設定" / "Concurrency").
 *
 * Returns null if the input is empty (concurrency unset), the number otherwise.
 */
async function readConcurrencyInputInProject(page: Page, labelText: string): Promise<number | "" | null> {
  return page.evaluate((label) => {
    // Locate the Concurrency card by h4 text
    const h4s = document.querySelectorAll("h4");
    let card: HTMLElement | null = null;
    for (const el of h4s) {
      const text = el.textContent?.trim() || "";
      if (text === "並列実行設定" || text === "Concurrency") {
        card = el.closest(".p-4, [class*='card']") as HTMLElement | null;
        if (card) break;
      }
    }
    if (!card) return null;

    // Find the label inside the card whose text matches and the sibling/descendant input
    const labels = card.querySelectorAll("label");
    for (const lbl of labels) {
      const t = lbl.textContent?.trim() || "";
      if (t.includes(label)) {
        // Walk up to find the wrapper div, then look for an <input type="number">
        let el: Element | null = lbl.parentElement;
        for (let depth = 0; el && depth < 3; depth++) {
          const input = el.querySelector("input[type='number']") as HTMLInputElement | null;
          if (input) {
            const value = input.value;
            if (value === "") return "";
            const num = Number(value);
            return Number.isFinite(num) ? num : null;
          }
          el = el.parentElement;
        }
      }
    }
    return null;
  }, labelText);
}

/**
 * Set the value of a number input by its label text inside the Concurrency card.
 * Empty string clears the input.
 */
async function setConcurrencyInputInProject(page: Page, labelText: string, value: string): Promise<boolean> {
  return page.evaluate(
    ({ label, val }) => {
      const h4s = document.querySelectorAll("h4");
      let card: HTMLElement | null = null;
      for (const el of h4s) {
        const text = el.textContent?.trim() || "";
        if (text === "並列実行設定" || text === "Concurrency") {
          card = el.closest(".p-4, [class*='card']") as HTMLElement | null;
          if (card) break;
        }
      }
      if (!card) return false;
      const labels = card.querySelectorAll("label");
      for (const lbl of labels) {
        const t = lbl.textContent?.trim() || "";
        if (t.includes(label)) {
          let el: Element | null = lbl.parentElement;
          for (let depth = 0; el && depth < 3; depth++) {
            const input = el.querySelector("input[type='number']") as HTMLInputElement | null;
            if (input) {
              const setter = Object.getOwnPropertyDescriptor(window.HTMLInputElement.prototype, "value")?.set;
              if (setter) {
                setter.call(input, val);
                input.dispatchEvent(new Event("input", { bubbles: true }));
                input.dispatchEvent(new Event("change", { bubbles: true }));
                return true;
              }
            }
            el = el.parentElement;
          }
        }
      }
      return false;
    },
    { label: labelText, val: value },
  );
}

/** Settings modal helpers */
async function openSettingsModal(page: Page): Promise<boolean> {
  const settingsBtn = await page.$('[data-testid="settings-button"]');
  if (!settingsBtn) return false;
  await settingsBtn.click();
  await page.waitForTimeout(CONFIG.NAVIGATION_DELAY_MS);
  // Heuristic: language-select exists in the modal
  const langSelect = await page.$('[data-testid="language-select"]');
  return !!langSelect;
}

async function closeSettingsModal(page: Page): Promise<void> {
  // Wait for debounced save
  await page.waitForTimeout(CONFIG.SETTINGS_SAVE_DELAY_MS);
  await page.keyboard.press("Escape");
  await page.waitForTimeout(CONFIG.ACTION_DELAY_MS);
}

async function expandConcurrencySettingsSection(page: Page): Promise<boolean> {
  return page.evaluate(() => {
    const buttons = document.querySelectorAll("button");
    for (const btn of buttons) {
      const text = btn.textContent?.trim() || "";
      if (text.includes("並列実行") || text.includes("Concurrency Defaults")) {
        const collapsible = btn.closest("[data-state]");
        if (collapsible?.getAttribute("data-state") === "open") return true;
        (btn as HTMLElement).click();
        return true;
      }
    }
    return false;
  });
}

/**
 * Inside the Concurrency Defaults card in Settings, read the input value
 * by label.
 */
async function readSettingsConcurrencyInput(page: Page, labelText: string): Promise<number | "" | null> {
  return page.evaluate((label) => {
    // Locate the card by its CardTitle text
    const titles = document.querySelectorAll("h3, h4, [data-slot='card-title']");
    let card: HTMLElement | null = null;
    for (const t of titles) {
      const text = t.textContent?.trim() || "";
      if (text.includes("並列実行") || text.includes("Concurrency Defaults")) {
        const found = t.closest("[class*='card'], [data-slot='card']") as HTMLElement | null;
        if (found) {
          card = found;
          break;
        }
      }
    }
    if (!card) return null;
    const labels = card.querySelectorAll("label");
    for (const lbl of labels) {
      const txt = lbl.textContent?.trim() || "";
      if (txt.includes(label)) {
        let el: Element | null = lbl.parentElement;
        for (let depth = 0; el && depth < 3; depth++) {
          const input = el.querySelector("input[type='number']") as HTMLInputElement | null;
          if (input) {
            const v = input.value;
            if (v === "") return "";
            const num = Number(v);
            return Number.isFinite(num) ? num : null;
          }
          el = el.parentElement;
        }
      }
    }
    return null;
  }, labelText);
}

async function setSettingsConcurrencyInput(page: Page, labelText: string, value: string): Promise<boolean> {
  return page.evaluate(
    ({ label, val }) => {
      const titles = document.querySelectorAll("h3, h4, [data-slot='card-title']");
      let card: HTMLElement | null = null;
      for (const t of titles) {
        const text = t.textContent?.trim() || "";
        if (text.includes("並列実行") || text.includes("Concurrency Defaults")) {
          const found = t.closest("[class*='card'], [data-slot='card']") as HTMLElement | null;
          if (found) {
            card = found;
            break;
          }
        }
      }
      if (!card) return false;
      const labels = card.querySelectorAll("label");
      for (const lbl of labels) {
        const txt = lbl.textContent?.trim() || "";
        if (txt.includes(label)) {
          let el: Element | null = lbl.parentElement;
          for (let depth = 0; el && depth < 3; depth++) {
            const input = el.querySelector("input[type='number']") as HTMLInputElement | null;
            if (input) {
              const setter = Object.getOwnPropertyDescriptor(window.HTMLInputElement.prototype, "value")?.set;
              if (setter) {
                setter.call(input, val);
                input.dispatchEvent(new Event("input", { bubbles: true }));
                input.dispatchEvent(new Event("change", { bubbles: true }));
                return true;
              }
            }
            el = el.parentElement;
          }
        }
      }
      return false;
    },
    { label: labelText, val: value },
  );
}

async function readEditorJson(page: Page): Promise<Record<string, unknown> | null> {
  const viewLines = await page.$(".monaco-editor .view-lines");
  if (!viewLines) return null;
  await viewLines.click();
  await page.waitForTimeout(300);
  await page.keyboard.press(selectAllKey);
  await page.waitForTimeout(200);
  await page.keyboard.press(copyKey);
  await page.waitForTimeout(200);
  const text = await page.evaluate(() =>
    (
      window as unknown as { electronAPI: { readClipboardText: () => Promise<string> } }
    ).electronAPI.readClipboardText(),
  );
  try {
    return JSON.parse(text);
  } catch {
    return null;
  }
}

async function writeEditorJson(page: Page, json: Record<string, unknown>): Promise<boolean> {
  const viewLines = await page.$(".monaco-editor .view-lines");
  if (!viewLines) return false;
  await viewLines.click();
  await page.waitForTimeout(300);
  await page.keyboard.press(selectAllKey);
  await page.waitForTimeout(200);
  const newText = JSON.stringify(json, null, 2);
  await page.evaluate(
    (t) =>
      (
        window as unknown as { electronAPI: { writeClipboardText: (s: string) => Promise<void> } }
      ).electronAPI.writeClipboardText(t),
    newText,
  );
  await page.waitForTimeout(200);
  await page.keyboard.press(pasteKey);
  // Wait for Monaco internal ops before any tab switch may dispose the editor
  await page.waitForTimeout(2000);
  return true;
}

/** Concurrency-aware view of script paramsfor assertions */
type ConcurrencyView = {
  imageConcurrency: unknown;
  movieConcurrency: unknown;
  audioConcurrency: unknown;
};

function pickConcurrency(json: Record<string, unknown> | null): ConcurrencyView {
  const get = (key: string): unknown => {
    const block = json?.[key] as Record<string, unknown> | undefined;
    return block?.concurrency;
  };
  return {
    imageConcurrency: get("imageParams"),
    movieConcurrency: get("movieParams"),
    audioConcurrency: get("audioParams"),
  };
}

async function readConcurrencyFromJsonTab(page: Page): Promise<ConcurrencyView | null> {
  if (!(await navigateToJsonTab(page))) return null;
  const json = await readEditorJson(page);
  if (!json) return null;
  return pickConcurrency(json);
}

async function navigateHome(page: Page): Promise<void> {
  await page.goto(page.url().split("#")[0] + "#/");
  await page.waitForTimeout(CONFIG.NAVIGATION_DELAY_MS);
}

async function clickCreateNewProject(page: Page): Promise<string | null> {
  const newBtn = await page.$('[data-testid="create-new-button"]');
  if (!newBtn) return null;
  await newBtn.click();
  await page.waitForTimeout(CONFIG.PROJECT_CREATE_DELAY_MS);
  const url = page.url();
  if (!url.includes("#/project/")) return null;
  // Extract project ID from url: .../#/project/<id>
  const m = url.match(/#\/project\/([^/?#]+)/);
  return m ? m[1] : null;
}

async function setProjectTitle(page: Page, title: string): Promise<boolean> {
  if (!(await navigateToJsonTab(page))) return false;
  const json = await readEditorJson(page);
  if (!json) return false;
  json.title = title;
  json.description = TEST_DESCRIPTION;
  const ok = await writeEditorJson(page, json);
  await page.waitForTimeout(CONFIG.EDITOR_SETTLE_DELAY_MS);
  return ok;
}

async function openProjectByTitle(page: Page, title: string): Promise<boolean> {
  await navigateHome(page);
  const link = await page.evaluate((t) => {
    const links = document.querySelectorAll('a[href*="#/project/"]');
    for (const a of links) {
      if (a.textContent?.includes(t)) {
        (a as HTMLElement).click();
        return true;
      }
    }
    return false;
  }, title);
  if (!link) return false;
  await page.waitForTimeout(CONFIG.NAVIGATION_DELAY_MS);
  return page.url().includes("#/project/");
}

// ==========================================
// Phase 1 – Settings
// ==========================================

async function testSettingsSection(page: Page) {
  console.log("\n=== 1a. Settings - Section presence + blank ===");

  if (!(await openSettingsModal(page))) {
    record("Open Settings modal", "FAIL", "Settings button not found / modal did not open");
    return;
  }
  record("Open Settings modal", "PASS", "Modal opened");

  const exists = await page.evaluate(() => {
    const titles = document.querySelectorAll("h3, h4, [data-slot='card-title']");
    return Array.from(titles).some((t) => {
      const txt = t.textContent?.trim() || "";
      return txt.includes("並列実行") || txt.includes("Concurrency Defaults");
    });
  });
  record("Concurrency Defaults card", exists ? "PASS" : "FAIL", exists ? "Found" : "Not found");
  if (!exists) {
    await closeSettingsModal(page);
    return;
  }

  const expanded = await expandConcurrencySettingsSection(page);
  record("Expand Concurrency section", expanded ? "PASS" : "FAIL", expanded ? "Toggled open" : "Could not expand");
  await page.waitForTimeout(CONFIG.ACTION_DELAY_MS);

  // Clear both fields → blank
  await setSettingsConcurrencyInput(page, "画像");
  // Try both Japanese and English label fragments (Card uses the same label key)
  const clearImageMovieJa = await setSettingsConcurrencyInput(page, "画像", "");
  const clearImageMovieEn = clearImageMovieJa ? false : await setSettingsConcurrencyInput(page, "Image", "");
  record(
    "Clear image/movie field",
    clearImageMovieJa || clearImageMovieEn ? "PASS" : "FAIL",
    clearImageMovieJa ? "ja label" : clearImageMovieEn ? "en label" : "Failed",
  );

  const clearAudioJa = await setSettingsConcurrencyInput(page, "音声", "");
  const clearAudioEn = clearAudioJa ? false : await setSettingsConcurrencyInput(page, "Audio", "");
  record(
    "Clear audio field",
    clearAudioJa || clearAudioEn ? "PASS" : "FAIL",
    clearAudioJa ? "ja label" : clearAudioEn ? "en label" : "Failed",
  );

  await closeSettingsModal(page);
}

async function testSettingsPersistence(page: Page) {
  console.log("\n=== 1b. Settings - Set values, persist across modal reopen ===");
  console.log(`  Test values: image/movie=${TEST_IMAGE_MOVIE}, audio=${TEST_AUDIO}`);

  // Set values
  if (!(await openSettingsModal(page))) {
    record("Open Settings (persistence)", "FAIL", "Modal did not open");
    return;
  }
  await expandConcurrencySettingsSection(page);
  await page.waitForTimeout(CONFIG.ACTION_DELAY_MS);

  const setImg =
    (await setSettingsConcurrencyInput(page, "画像", String(TEST_IMAGE_MOVIE))) ||
    (await setSettingsConcurrencyInput(page, "Image", String(TEST_IMAGE_MOVIE)));
  const setAud =
    (await setSettingsConcurrencyInput(page, "音声", String(TEST_AUDIO))) ||
    (await setSettingsConcurrencyInput(page, "Audio", String(TEST_AUDIO)));
  record("Set image/movie", setImg ? "PASS" : "FAIL", setImg ? String(TEST_IMAGE_MOVIE) : "Failed");
  record("Set audio", setAud ? "PASS" : "FAIL", setAud ? String(TEST_AUDIO) : "Failed");

  await closeSettingsModal(page);

  // Reopen, verify values persisted
  if (!(await openSettingsModal(page))) {
    record("Reopen Settings", "FAIL", "Modal did not open");
    return;
  }
  await expandConcurrencySettingsSection(page);
  await page.waitForTimeout(CONFIG.ACTION_DELAY_MS);

  const imgVal =
    (await readSettingsConcurrencyInput(page, "画像")) ?? (await readSettingsConcurrencyInput(page, "Image"));
  const audVal =
    (await readSettingsConcurrencyInput(page, "音声")) ?? (await readSettingsConcurrencyInput(page, "Audio"));
  record(
    "image/movie persisted",
    imgVal === TEST_IMAGE_MOVIE ? "PASS" : "FAIL",
    `Got ${JSON.stringify(imgVal)}, expected ${TEST_IMAGE_MOVIE}`,
  );
  record(
    "audio persisted",
    audVal === TEST_AUDIO ? "PASS" : "FAIL",
    `Got ${JSON.stringify(audVal)}, expected ${TEST_AUDIO}`,
  );

  await closeSettingsModal(page);
}

// ==========================================
// Phase 2 – Inject on create (Settings set)
// ==========================================

async function testInjectOnCreate(page: Page): Promise<string | null> {
  console.log("\n=== 2a. New project picks up global concurrency ===");

  await navigateHome(page);
  const projectId = await clickCreateNewProject(page);
  if (!projectId) {
    record("Create project (inject)", "FAIL", "create-new-button not found / no navigation");
    return null;
  }
  record("Create project (inject)", "PASS", `id=${projectId}`);

  await setProjectTitle(page, TITLE_INJECT);

  const cv = await readConcurrencyFromJsonTab(page);
  if (!cv) {
    record("Read JSON after create (inject)", "FAIL", "Could not read JSON");
    return projectId;
  }

  record(
    "imageParams.concurrency injected",
    cv.imageConcurrency === TEST_IMAGE_MOVIE ? "PASS" : "FAIL",
    `Got ${JSON.stringify(cv.imageConcurrency)}, expected ${TEST_IMAGE_MOVIE}`,
  );
  record(
    "movieParams.concurrency injected",
    cv.movieConcurrency === TEST_IMAGE_MOVIE ? "PASS" : "FAIL",
    `Got ${JSON.stringify(cv.movieConcurrency)}, expected ${TEST_IMAGE_MOVIE}`,
  );
  record(
    "audioParams.concurrency injected",
    cv.audioConcurrency === TEST_AUDIO ? "PASS" : "FAIL",
    `Got ${JSON.stringify(cv.audioConcurrency)}, expected ${TEST_AUDIO}`,
  );

  return projectId;
}

// ==========================================
// Phase 3 – Inject on create (Settings blank)
// ==========================================

async function clearSettingsConcurrency(page: Page) {
  if (!(await openSettingsModal(page))) {
    record("Clear Settings concurrency", "FAIL", "Modal did not open");
    return;
  }
  await expandConcurrencySettingsSection(page);
  await page.waitForTimeout(CONFIG.ACTION_DELAY_MS);
  await setSettingsConcurrencyInput(page, "画像", "");
  await setSettingsConcurrencyInput(page, "Image", "");
  await setSettingsConcurrencyInput(page, "音声", "");
  await setSettingsConcurrencyInput(page, "Audio", "");
  await closeSettingsModal(page);
}

async function testNoInjectWhenBlank(page: Page): Promise<string | null> {
  console.log("\n=== 3a. Blank Settings → new project has no concurrency fields ===");

  await clearSettingsConcurrency(page);
  await navigateHome(page);
  const projectId = await clickCreateNewProject(page);
  if (!projectId) {
    record("Create project (blank)", "FAIL", "create-new-button not found");
    return null;
  }
  record("Create project (blank)", "PASS", `id=${projectId}`);

  await setProjectTitle(page, TITLE_BLANK);

  const cv = await readConcurrencyFromJsonTab(page);
  if (!cv) {
    record("Read JSON after create (blank)", "FAIL", "Could not read JSON");
    return projectId;
  }

  record(
    "imageParams.concurrency absent",
    cv.imageConcurrency === undefined ? "PASS" : "FAIL",
    `Got ${JSON.stringify(cv.imageConcurrency)}`,
  );
  record(
    "movieParams.concurrency absent",
    cv.movieConcurrency === undefined ? "PASS" : "FAIL",
    `Got ${JSON.stringify(cv.movieConcurrency)}`,
  );
  record(
    "audioParams.concurrency absent",
    cv.audioConcurrency === undefined ? "PASS" : "FAIL",
    `Got ${JSON.stringify(cv.audioConcurrency)}`,
  );

  return projectId;
}

// ==========================================
// Phase 4 – Existing project untouched
// ==========================================

async function testExistingProjectUntouched(page: Page) {
  console.log("\n=== 4a. Existing project not mutated when reopened with new global ===");

  // Re-set Settings to non-blank values (different from earlier)
  if (!(await openSettingsModal(page))) {
    record("Re-set Settings (untouched)", "FAIL", "Modal did not open");
    return;
  }
  await expandConcurrencySettingsSection(page);
  await page.waitForTimeout(CONFIG.ACTION_DELAY_MS);
  const setImg2 =
    (await setSettingsConcurrencyInput(page, "画像", String(TEST_IMAGE_MOVIE_2))) ||
    (await setSettingsConcurrencyInput(page, "Image", String(TEST_IMAGE_MOVIE_2)));
  const setAud2 =
    (await setSettingsConcurrencyInput(page, "音声", String(TEST_AUDIO_2))) ||
    (await setSettingsConcurrencyInput(page, "Audio", String(TEST_AUDIO_2)));
  record("Re-set Settings (untouched)", setImg2 && setAud2 ? "PASS" : "FAIL", setImg2 && setAud2 ? "OK" : "Failed");
  await closeSettingsModal(page);

  // Open the BLANK project from Phase 3 and verify JSON still has no concurrency
  if (!(await openProjectByTitle(page, TITLE_BLANK))) {
    record("Reopen blank project", "FAIL", `Project not found by title "${TITLE_BLANK}"`);
    return;
  }
  record("Reopen blank project", "PASS", "Navigated to project");

  const cv = await readConcurrencyFromJsonTab(page);
  if (!cv) {
    record("Read JSON on reopen", "FAIL", "Could not read JSON");
    return;
  }
  record(
    "imageParams.concurrency still absent",
    cv.imageConcurrency === undefined ? "PASS" : "FAIL",
    `Got ${JSON.stringify(cv.imageConcurrency)}`,
  );
  record(
    "movieParams.concurrency still absent",
    cv.movieConcurrency === undefined ? "PASS" : "FAIL",
    `Got ${JSON.stringify(cv.movieConcurrency)}`,
  );
  record(
    "audioParams.concurrency still absent",
    cv.audioConcurrency === undefined ? "PASS" : "FAIL",
    `Got ${JSON.stringify(cv.audioConcurrency)}`,
  );
}

// ==========================================
// Phase 5 – Style tab per-project edits
// ==========================================

async function testStyleTabPerProject(page: Page) {
  console.log("\n=== 5. Style tab per-project edits ===");

  // Use the INJECT project (already has values)
  if (!(await openProjectByTitle(page, TITLE_INJECT))) {
    record("Open INJECT project (style tab)", "FAIL", `Project not found: ${TITLE_INJECT}`);
    return;
  }

  if (!(await navigateToStyleTab(page))) {
    record("Navigate Style tab", "FAIL", "Style tab not found");
    return;
  }
  await page.waitForTimeout(CONFIG.NAVIGATION_DELAY_MS);

  if (!(await scrollToConcurrencySection(page))) {
    record("Scroll to Concurrency section", "FAIL", "Section h4 not found");
    return;
  }
  record("Scroll to Concurrency section", "PASS", "Found");

  // 5a. image/movie writes both
  const newImageMovie = OVERRIDE_IMAGE_MOVIE;
  const wroteImg =
    (await setConcurrencyInputInProject(page, "画像", String(newImageMovie))) ||
    (await setConcurrencyInputInProject(page, "Image", String(newImageMovie)));
  record("Write image/movie input", wroteImg ? "PASS" : "FAIL", wroteImg ? String(newImageMovie) : "Failed");
  await page.waitForTimeout(CONFIG.ACTION_DELAY_MS);

  // Verify both imageParams and movieParams in JSON
  const cv1 = await readConcurrencyFromJsonTab(page);
  if (!cv1) {
    record("Read JSON after image/movie write", "FAIL", "Could not read JSON");
    return;
  }
  record(
    "imageParams.concurrency = override",
    cv1.imageConcurrency === newImageMovie ? "PASS" : "FAIL",
    `Got ${JSON.stringify(cv1.imageConcurrency)}, expected ${newImageMovie}`,
  );
  record(
    "movieParams.concurrency = override",
    cv1.movieConcurrency === newImageMovie ? "PASS" : "FAIL",
    `Got ${JSON.stringify(cv1.movieConcurrency)}, expected ${newImageMovie}`,
  );
  record(
    "audioParams.concurrency unchanged",
    cv1.audioConcurrency === TEST_AUDIO ? "PASS" : "FAIL",
    `Got ${JSON.stringify(cv1.audioConcurrency)}, expected ${TEST_AUDIO}`,
  );

  // 5b. audio override
  await navigateToStyleTab(page);
  await page.waitForTimeout(CONFIG.NAVIGATION_DELAY_MS);
  await scrollToConcurrencySection(page);

  const newAudio = OVERRIDE_AUDIO;
  const wroteAud =
    (await setConcurrencyInputInProject(page, "音声", String(newAudio))) ||
    (await setConcurrencyInputInProject(page, "Audio", String(newAudio)));
  record("Write audio input", wroteAud ? "PASS" : "FAIL", wroteAud ? String(newAudio) : "Failed");
  await page.waitForTimeout(CONFIG.ACTION_DELAY_MS);

  const cv2 = await readConcurrencyFromJsonTab(page);
  if (!cv2) {
    record("Read JSON after audio write", "FAIL", "Could not read JSON");
    return;
  }
  record(
    "audioParams.concurrency = override",
    cv2.audioConcurrency === newAudio ? "PASS" : "FAIL",
    `Got ${JSON.stringify(cv2.audioConcurrency)}, expected ${newAudio}`,
  );

  // 5c. clearing → undefined / removed from JSON
  await navigateToStyleTab(page);
  await page.waitForTimeout(CONFIG.NAVIGATION_DELAY_MS);
  await scrollToConcurrencySection(page);

  await setConcurrencyInputInProject(page, "画像", "");
  await setConcurrencyInputInProject(page, "Image", "");
  await setConcurrencyInputInProject(page, "音声", "");
  await setConcurrencyInputInProject(page, "Audio", "");
  await page.waitForTimeout(CONFIG.ACTION_DELAY_MS);

  const cv3 = await readConcurrencyFromJsonTab(page);
  if (!cv3) {
    record("Read JSON after clear", "FAIL", "Could not read JSON");
    return;
  }
  record(
    "imageParams.concurrency cleared",
    cv3.imageConcurrency === undefined ? "PASS" : "FAIL",
    `Got ${JSON.stringify(cv3.imageConcurrency)}`,
  );
  record(
    "movieParams.concurrency cleared",
    cv3.movieConcurrency === undefined ? "PASS" : "FAIL",
    `Got ${JSON.stringify(cv3.movieConcurrency)}`,
  );
  record(
    "audioParams.concurrency cleared",
    cv3.audioConcurrency === undefined ? "PASS" : "FAIL",
    `Got ${JSON.stringify(cv3.audioConcurrency)}`,
  );
}

// ==========================================
// Phase 6 – JSON → UI round-trip
// ==========================================

async function testJsonToUI(page: Page) {
  console.log("\n=== 6. JSON → UI round-trip ===");

  // Use the INJECT project
  if (!(await openProjectByTitle(page, TITLE_INJECT))) {
    record("Open project (json→ui)", "FAIL", `Project not found: ${TITLE_INJECT}`);
    return;
  }

  if (!(await navigateToJsonTab(page))) {
    record("Navigate JSON tab (json→ui)", "FAIL", "JSON tab not found");
    return;
  }

  const json = await readEditorJson(page);
  if (!json) {
    record("Read JSON (json→ui)", "FAIL", "Could not read");
    return;
  }

  const FROM_JSON_IMAGE_MOVIE = 13;
  const FROM_JSON_AUDIO = 17;

  json.imageParams = { ...((json.imageParams as Record<string, unknown>) ?? {}), concurrency: FROM_JSON_IMAGE_MOVIE };
  json.movieParams = { ...((json.movieParams as Record<string, unknown>) ?? {}), concurrency: FROM_JSON_IMAGE_MOVIE };
  json.audioParams = { ...((json.audioParams as Record<string, unknown>) ?? {}), concurrency: FROM_JSON_AUDIO };

  const wrote = await writeEditorJson(page, json);
  record("Write concurrency via JSON", wrote ? "PASS" : "FAIL", wrote ? "OK" : "Failed");

  // Wait for Monaco to settle before leaving JSON tab
  await page.waitForTimeout(CONFIG.EDITOR_SETTLE_DELAY_MS);

  if (!(await navigateToStyleTab(page))) {
    record("Navigate Style tab (json→ui)", "FAIL", "Style tab not found");
    return;
  }
  await page.waitForTimeout(CONFIG.NAVIGATION_DELAY_MS);
  await scrollToConcurrencySection(page);

  const imgVal =
    (await readConcurrencyInputInProject(page, "画像")) ?? (await readConcurrencyInputInProject(page, "Image"));
  const audVal =
    (await readConcurrencyInputInProject(page, "音声")) ?? (await readConcurrencyInputInProject(page, "Audio"));
  record(
    "image/movie input reflects JSON",
    imgVal === FROM_JSON_IMAGE_MOVIE ? "PASS" : "FAIL",
    `Got ${JSON.stringify(imgVal)}, expected ${FROM_JSON_IMAGE_MOVIE}`,
  );
  record(
    "audio input reflects JSON",
    audVal === FROM_JSON_AUDIO ? "PASS" : "FAIL",
    `Got ${JSON.stringify(audVal)}, expected ${FROM_JSON_AUDIO}`,
  );
}

// ==========================================
// Phase 7 – Console health
// ==========================================

async function testConsoleHealth(monitor: ConsoleMonitor) {
  console.log("\n=== 7. Console health ===");
  record(
    "Console errors",
    monitor.errors.length === 0 ? "PASS" : "FAIL",
    monitor.errors.length === 0 ? "No errors" : `${monitor.errors.length} error(s)`,
  );
  monitor.errors.slice(0, 5).forEach((e) => console.log(`    ERROR: ${e.substring(0, 200)}`));
  record(
    "Console warnings",
    monitor.warnings.length === 0 ? "PASS" : "WARN",
    monitor.warnings.length === 0 ? "No warnings" : `${monitor.warnings.length} warning(s)`,
  );
}

// ==========================================
// Main
// ==========================================

(async () => {
  let exitCode = 0;
  const resources: { browser: Browser | null } = { browser: null };

  console.log("\n========================================");
  console.log("  Concurrency QA (no API)");
  console.log(`  runId: ${runId}`);
  console.log(`  test values: image/movie=${TEST_IMAGE_MOVIE}, audio=${TEST_AUDIO}`);
  console.log(`  reset values: image/movie=${TEST_IMAGE_MOVIE_2}, audio=${TEST_AUDIO_2}`);
  console.log(`  override values: image/movie=${OVERRIDE_IMAGE_MOVIE}, audio=${OVERRIDE_AUDIO}`);
  console.log("========================================");

  try {
    resources.browser = await connectCDP();
    const contexts = resources.browser.contexts();
    const page = findAppPage(contexts);
    console.log(`Found app page: ${page.url()}`);

    const monitor = createConsoleMonitor(page);
    monitor.start();

    // Navigate home; dismiss any lingering modal
    await navigateHome(page);
    const overlay = await page.$('[data-state="open"][aria-hidden="true"]');
    if (overlay) {
      await page.keyboard.press("Escape");
      await page.waitForTimeout(CONFIG.ACTION_DELAY_MS);
    }

    // Phase 1
    console.log("\n==========================================");
    console.log("  Phase 1: Settings");
    console.log("==========================================");
    await testSettingsSection(page);
    await testSettingsPersistence(page);

    // Phase 2
    console.log("\n==========================================");
    console.log("  Phase 2: Inject on create (Settings set)");
    console.log("==========================================");
    await testInjectOnCreate(page);

    // Phase 3
    console.log("\n==========================================");
    console.log("  Phase 3: Inject on create (Settings blank)");
    console.log("==========================================");
    await testNoInjectWhenBlank(page);

    // Phase 4
    console.log("\n==========================================");
    console.log("  Phase 4: Existing project untouched");
    console.log("==========================================");
    await testExistingProjectUntouched(page);

    // Phase 5
    console.log("\n==========================================");
    console.log("  Phase 5: Style tab per-project edits");
    console.log("==========================================");
    await testStyleTabPerProject(page);

    // Phase 6
    console.log("\n==========================================");
    console.log("  Phase 6: JSON → UI round-trip");
    console.log("==========================================");
    await testJsonToUI(page);

    // Phase 7
    console.log("\n==========================================");
    console.log("  Phase 7: Console health");
    console.log("==========================================");
    await testConsoleHealth(monitor);

    monitor.stop();

    await navigateHome(page);

    // Summary
    console.log("\n========================================");
    console.log("  TEST SUMMARY");
    console.log("========================================");
    const pass = results.filter((r) => r.status === "PASS").length;
    const fail = results.filter((r) => r.status === "FAIL").length;
    const warn = results.filter((r) => r.status === "WARN").length;
    console.log(`  PASS: ${pass}`);
    console.log(`  FAIL: ${fail}`);
    console.log(`  WARN: ${warn}`);
    console.log(`  TOTAL: ${results.length}`);
    console.log("----------------------------------------");
    if (fail > 0) {
      console.log("\n  Failed tests:");
      results.filter((r) => r.status === "FAIL").forEach((r) => console.log(`    ✗ ${r.name}: ${r.detail}`));
    }
    exitCode = fail === 0 ? 0 : 1;
    console.log("\n========================================");
  } catch (error) {
    console.error("\nTest suite failed:", error);
    exitCode = 1;
  } finally {
    if (resources.browser) {
      await resources.browser.close().catch(() => {});
    }
    process.exit(exitCode);
  }
})();
