name: Bug report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Open MulmoCast app
        2. Create/open project
        3. Perform action in GUI (e.g., generate content, edit script)
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: dropdown
    id: install-method
    attributes:
      label: Installation Method
      description: How did you install MulmoCast App?
      options:
        - GitHub Actions macOS build (DMG download)
        - GitHub Actions Windows build (installer download)
        - Development build (yarn start from source)
        - Other
    validations:
      required: true

  - type: input
    id: app-version
    attributes:
      label: App Version
      description: |
        - Check "About MulmoCast App" in the app menu
        - For development build: Check package.json or git commit hash
      placeholder: "e.g., 1.2.27 or commit abc123"
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: |
        If applicable, add screenshots to help explain your problem.
        You can drag and drop images directly into this text area after creating the issue.
      placeholder: |
        Screenshots will help us understand the issue better.
        After creating this issue, you can drag and drop image files here.
    validations:
      required: false

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What OS are you using?
      options:
        - macOS
        - Windows
        - Linux
        - Other
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: OS Version
      description: e.g., macOS 14.0, Windows 11, Ubuntu 22.04
      placeholder: "Version"
    validations:
      required: false


  - type: textarea
    id: project-files
    attributes:
      label: Project Files
      description: If relevant, paste your project script or configuration inside the provided template below
      value: |
        <details>
        <summary>Project Script/Configuration (click to expand)</summary>
        
        ```json
        {
          "title": "Replace this with your project script",
          "beats": [...]
        }
        ```
        
        </details>
    validations:
      required: false

  - type: textarea
    id: error-output
    attributes:
      label: Error Output
      description: Paste error messages, console logs, or error dialogs inside the provided template below
      value: |
        <details>
        <summary>Error logs/dialogs (click to expand)</summary>
        
        ```
        Replace this with your error output or error dialog text
        ```
        
        </details>
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here (e.g., relevant API key settings without sensitive data, app configuration).
    validations:
      required: false
