name: Feature request
description: Suggest an idea for MulmoCast
title: "[Feature]: "
labels: ["enhancement"]
projects: ["https://github.com/orgs/receptron/projects/3"] 
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!

  - type: checkboxes
    id: pre-flight-checks
    attributes:
      label: Preliminary Checks
      description: Before submitting, please make sure you have done the following.
      options:
        - label: I have searched the existing issues and have not found a similar feature request.
          required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: I would like to be able to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: Other approaches that might work...
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: How important is this feature to you?
      description: Help us understand the priority
      options:
        - Critical - blocking my work
        - High - significant improvement to workflow
        - Medium - nice to have
        - Low - minor enhancement
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case for this feature
      placeholder: |
        I need this feature for...
        It would help me to...
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation suggestions
      description: If you have ideas about how this could be implemented, please share them
      placeholder: This could be implemented by...
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute to this feature?
      options:
        - label: I'm willing to submit a PR for this feature

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context, mockups, or screenshots about the feature request here.
    validations:
      required: false