name: Playwright Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        yarn install
        # Playwrightの依存関係をインストール
        npx playwright install-deps chromium
        
    - name: Build Electron app
      run: yarn build
      
    - name: Run Playwright tests (with xvfb)
      run: |
        # Xvfbを使用してヘッドレスで実行
        xvfb-run -a node test/electron-playwright-ci-test.js
      env:
        CI: true
        NODE_ENV: test
        
    - name: Upload test artifacts
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results
        path: |
          test/*.png
          test/test-failure.png
        retention-days: 7